# Generated by Django 2.0.4 on 2018-04-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(unique=True, verbose_name='ID')),
                ('lat', models.IntegerField(verbose_name='Latitude')),
                ('lon', models.IntegerField(verbose_name='Longitude')),
            ],
        ),
    ]
