# Generated by Django 2.0.4 on 2018-04-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='reserved',
            field=models.IntegerField(default=0, verbose_name='Reserved'),
        ),
    ]
