# Generated by Django 2.0.4 on 2018-04-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_parkingspot_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='lat',
            field=models.FloatField(verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='lon',
            field=models.FloatField(verbose_name='Longitude'),
        ),
    ]
